title: Your Title
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
title: WOWMON
description: > # this means to ignore newlines until "baseurl:"
# Build settings
markdown: kramdown

logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
